TENANT_ID = 'ed49fe9a-6eea-47e6-bf52-ee9ecb5da807'
CLIENT_ID = '1d3fffdb-b776-4f76-b8b9-2f87049b098e'
CLIENT_SECRET = 'gc98Q~AOfrdoUSlfuWyBzTvNgdB3uaF8Y31_Hczf'
SENDER_EMAIL= 'juan.vallejo@igac.gov.co'
SHAREPOINT_SITE_URL= 'https://igacoffice365.sharepoint.com/sites/SAF'

# Admin Credentials for Request Management System
[admin_credentials]

[admin_credentials."Subdirección Administrativa y Financiera"]

[admin_credentials."Subdirección Administrativa y Financiera".Almacén]
usuario = "admin_almacen"
password = "Almacen3455*"

[admin_credentials."Subdirección Administrativa y Financiera".Archivo]
usuario = "admin_archivo"
password = "Archivo4790*"

[admin_credentials."Subdirección Administrativa y Financiera".Contabilidad]
usuario = "admin_contabilidad"
password = "Contable9865#"

[admin_credentials."Subdirección Administrativa y Financiera".Contractual]
usuario = "admin_contractual"
password = "Contractual6518!"

[admin_credentials."Subdirección Administrativa y Financiera".Correspondencia]
usuario = "admin_correspondencia"
password = "Correo3981$"

[admin_credentials."Subdirección Administrativa y Financiera".Infraestructura]
usuario = "admin_infraestructura"
password = "Infraestructura2387!"

[admin_credentials."Subdirección Administrativa y Financiera"."Operación Logística SAF"]
usuario = "admin_operacion"
password = "Logistica0978#"

[admin_credentials."Subdirección Administrativa y Financiera".Presupuesto]
usuario = "admin_presupuesto"
password = "Presupuesto3425$"

[admin_credentials."Subdirección Administrativa y Financiera".Tesorería]
usuario = "admin_tesoreria"
password = "Tesoreria9248!"

[admin_credentials."Subdirección Administrativa y Financiera".Tiquetes]
usuario = "admin_tiquetes"
password = "Tiquetes9845$"

[admin_credentials."Subdirección Administrativa y Financiera".Transporte]
usuario = "admin_transporte"
password = "Transporte5926*"

[admin_credentials."Oficina Asesora de Comunicaciones"]

[admin_credentials."Oficina Asesora de Comunicaciones"."Comunicación Externa"]
usuario = "admin_com_externa"
password = "ComExt2024!"

[admin_credentials."Oficina Asesora de Comunicaciones"."Comunicación Interna"]
usuario = "admin_com_interna"
password = "ComInt2024!"
